export const faculties = [
  "Edebiyat Fakültesi",
  "Eğitim Fakültesi",
  "Keşan Hakkı Yörük Sağlık Yüksekokulu",
  "Keşan Yusuf Çapraz Uygulamalı Bilimler Yüksekokulu",
  "Mühendislik Fakültesi",
  "Fen Fakültesi",
  "İktisadi ve İdari Bilimler Fakültesi",
  "Diş Hekimliği Fakültesi",
  "Eczacılık Fakültesi",
  "Sağlık Bilimleri Fakültesi",
  "Mimarlık Fakültesi",
  "İlahiyat Fakültesi",
  "Güzel Sanatlar Fakültesi",
  "Uygulamalı Bilimler Fakültesi",
  "Uzunköprü Uygulamalı Bilimler Yüksekokulu",
  "Tıp Fakültesi",
  "Arda Meslek Yüksekokulu",
  "Havsa Meslek Yüksekokulu",
  "Edirne Sosyal Bilimler Meslek Yüksekokulu",
  "Edirne Teknik Bilimler Meslek Yüksekokulu",
  "Tunca Meslek Yüksekokulu",
  "Uzunköprü Meslek Yüksekokulu",
  "Keşan Meslek Yüksekokulu",
  "Sağlık Hizmetleri Meslek Yüksekokulu",
  "İpsala Meslek Yüksekokulu",
  "Şehit Ressam Hasan Rıza Güzel Sanatlar Meslek Yüksekokulu",
];

export const departments = [
  // Lisans Programları
  "Acil Yardım ve Afet Yönetimi",
  "Almanca Mütercim ve Tercümanlık",
  "Almanca Öğretmenliği",
  "Arkeoloji",
  "Arnavut Dili ve Edebiyatı",
  "Bankacılık ve Sigortacılık (Lisans)",
  "Beslenme ve Diyetetik",
  "Bilgisayar Mühendisliği",
  "Bilişim Sistemleri ve Teknolojileri",
  "Biyoloji",
  "Boşnak Dili ve Edebiyatı",
  "Bulgarca Mütercim ve Tercümanlık",
  "Çağdaş Yunan Dili ve Edebiyatı",
  "Çalışma Ekonomisi ve Endüstri İlişkileri",
  "Diş Hekimliği",
  "Eczacılık",
  "Ekonometri",
  "Elektrik-Elektronik Mühendisliği",
  "Fen Bilgisi Öğretmenliği",
  "Finans ve Bankacılık",
  "Fizik",
  "Fizyoterapi ve Rehabilitasyon",
  "Genetik ve Biyomühendislik",
  "Gıda Mühendisliği",
  "Gümrük İşletme",
  "Halkla İlişkiler ve Reklamcılık",
  "Hemşirelik",
  "İç Mimarlık",
  "İktisat",
  "İlahiyat",
  "İletişim ve Tasarımı",
  "İlköğretim Matematik Öğretmenliği",
  "İngilizce Mütercim ve Tercümanlık",
  "İngilizce Öğretmenliği",
  "İşletme",
  "Kimya",
  "Makine Mühendisliği",
  "Maliye (Lisans)",
  "Matematik",
  "Mimarlık",
  "Muhasebe ve Finans Yönetimi",
  // Önlisans Programları
  "Ağız ve Diş Sağlığı",
  "Ameliyathane Hizmetleri",
  "Anestezi",
  "Aşçılık",
  "Bankacılık ve Sigortacılık (Önlisans)",
  "Basım ve Yayım Teknolojileri",
  "Bilgisayar Programcılığı",
  "Bilgisayar Programcılığı (Uzaktan Öğretim)",
  "Biyomedikal Cihaz Teknolojisi",
  "Büro Yönetimi ve Yönetici Asistanlığı",
  "Çocuk Gelişimi",
  "Dezenfeksiyon, Sterilizasyon ve Antisepsi Teknikerliği",
  "Dış Ticaret",
  "Eczane Hizmetleri",
  "Elektrik",
  "Elektronik Teknolojisi",
  "Elektronörofizyoloji",
  "Fizyoterapi",
  "Geleneksel El Sanatları",
  "Gıda Teknolojisi",
  "Giyim Üretim Teknolojisi",
  "Grafik Tasarımı",
  "Halkla İlişkiler ve Tanıtım",
  "Harita ve Kadastro",
  "Hibrid ve Elektrikli Taşıtlar Teknolojisi",
  "İlk ve Acil Yardım",
  "İnsansız Araç Teknikerliği",
  "İş Sağlığı ve Güvenliği",
  "İşletme Yönetimi",
  "Kimya Teknolojisi",
  "Kuyumculuk ve Takı Tasarımı",
  "Laborant ve Veteriner Sağlık",
  "Laboratuvar Teknolojisi",
  "Lojistik",
  "Mahkeme Büro Hizmetleri",
  "Makine",
  "Maliye (Önlisans)",
  "Mekatronik",
  "Mimari Dekoratif Sanatlar",
  "Mimari Restorasyon",
  "Mobil Teknolojileri",
  "Muhasebe ve Vergi Uygulamaları",
  "Odyometri",
  "Ortopedik Protez ve Ortez",
  "Otomotiv Teknolojisi",
  "Patoloji Laboratuvar Teknikleri",
  "Pazarlama",
  "Radyo ve Televizyon Programcılığı",
  "Saç Bakımı ve Güzellik Hizmetleri",
  "Sağlık Bilgi Sistemleri Teknikerliği",
  "Sağlık Kurumları İşletmeciliği",
  "Sivil Savunma ve İtfaiyecilik",
  "Sosyal Hizmetler",
  "Spor Yönetimi",
  "Tıbbi Dokümantasyon ve Sekreterlik",
  "Tıbbi Görüntüleme Teknikleri",
  "Tıbbi Laboratuvar Teknikleri",
  "Turizm ve Otel İşletmeciliği",
  "Turizm ve Seyahat Hizmetleri",
  "Yaşlı Bakımı",
  // Yüksek Lisans ve Doktora
  "Yüksek Lisans",
  "Doktora",
];
